name: Build and Deploy
run-name: Deploy docs 🚀
on: [push]
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm docs:build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: docs/.vitepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
